# Generated by Django 5.1.1 on 2024-10-04 06:45

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_txt', models.TextField()),
                ('body_txt', models.TextField()),
                ('date', models.CharField(max_length=12)),
                ('time', models.CharField(default='00:00', max_length=12)),
                ('picname', models.TextField()),
                ('picurl', models.TextField(default='-')),
                ('writer', models.CharField(max_length=100)),
                ('catname', models.CharField(default='-', max_length=100)),
                ('catid', models.IntegerField(default=0)),
                ('ocatid', models.IntegerField(default=0)),
                ('show', models.IntegerField(default=0)),
                ('tag', models.TextField(default='')),
                ('act', models.IntegerField(default=0)),
                ('rand', models.IntegerField(default=0)),
            ],
        ),
    ]
